### ISSUE TITLE
root.<parent_domain_name> command fails when trying to start geodesic shell

### ISSUE THREAD

**Issue by Martaver** [cloudposse/root.cloudposse.co#7]
Whatever the `make install` is doing to install the shell wrapper doesn't work for me. Running `root.<parent_domain_name>` for me just responds with:
```
root.<parent_domain_name>: command not found
```

Workaround for now is to use `make run` instead.

**Comment by osterman** [comment]
@Martaver ok, this is related to a `PATH` issue, I suppose, on WSL. Can you show me what your `PATH` environment variable looks like? If it's a path issue, we can easily fix this.

**Comment by osterman** [comment]
Very odd. Actually, I do see it in the `PATH`. Not sure why it's not finding it. It's just a regular shell script. Can you confirm it's mode is `755`?

![image](https://user-images.githubusercontent.com/52489/43369079-616c27bc-931c-11e8-8507-d4c108c37d7a.png)

**Comment by osterman** [comment]
(also, I assume that `<parent_domain_name>` is a placeholder representing something like `example.com`)

**Comment by osterman** [comment]
This has been fixed in all reference architectures: https://github.com/cloudposse/prod.cloudposse.co/commit/b841e0a13ff3708054dfdd98f744b7fd2674fc42#diff-b67911656ef5d18c4ae36cb6741b7965R30

Thanks for taking the time to report the issue.
