### ISSUE TITLE
geodesic shell doesn't mount $HOME into /localhost correctly

### ISSUE THREAD

**Issue by Martaver** [cloudposse/root.cloudposse.co#8]
Using `make run` to launch geodesic shell, running `assume-role` fails with:
```
aws-vault: error: Failed to get credentials for <parent_domain_name>: The specified item could not be found in the keyring.
```
When I run `aws-vault`, I get no credentials listed. `~/.aws/config` doesn't exist.

Outside of the shell, `aws-vault` lists all my credentials correctly.

Could this be because I'm running the shell with `make run` instead of the configured `root.<parent_company_name>` script?

**Comment by osterman** [comment]
When you setup the aws-vault credentials for the first time, did you do it natively or a geodesic shell. If you did it natively, chances are that AWS_VAULT_BACKEND=file was not set, so it defaulted to your OS keychain. This won’t work across OS boundaries, so we recommend using the file mode. After setting it to file mode, you will need to reinitialize the source profile credentials with ‘aws-vault add ...’

**Comment by Martaver** [comment]
Yeah, I read about that and I've been using `AWS_VAULT_BACKEND=file` the whole time. So it should be fine, if docker mounts the correct directory.

The geodesic Dockerfile sets `/localhost/.aws/config` as `AWS_CONFIG_FILE` - but this doesn't exist on my system. `AWS_CONFIG_FILE` is `~/.aws/config` for me. Also neither of these seem to exist from inside the shell. Could it be an issue with the required volumes not being mounted?

**Comment by Martaver** [comment]
I just noticed this error during the shell's startup also:
```
aws-vault: error: Server failed: exit status 2
```

**Comment by Martaver** [comment]
So I figured out that ~ is the same as $HOME, which is what the vendor/root.<parent_domain_name> script bind mounts as a volume. can confirm that $HOME/.aws/config on my local environment contains the credentials, and at the same time `cat /localhost/.aws/config` is empty from geodesic. Something isn't mounting my $HOME properly. I wonder if it's a permissions issue, but running in sudo doesn't seem to help. Also, geodesic is fired up in privileged mode...

**Comment by Martaver** [comment]
Yeah, whatever this is, it's definitely a problem to do with the `$HOST/localhost` volume mount.

No matter what I do with permissions or content in my $HOME folder, or running in sudo, all I ever see in geodesic's `/localhost` is:

```
.  ..  .aws  .awsvault  .geodesic
```

**Comment by osterman** [comment]
> aws-vault: error: Server failed: exit status 2 

# reason 1

This usually happens if you have two shells running concurrently because `aws-vault` attempts to bind to `169.254.169.254` (metadata discovery address). I'm going to add an issue to track this since it's been a problem for a while. Fix should be pretty easy. 

For now, only run one shell at a time. 

# reason 2

Maybe you're not running with `--privileged` mode which is required in order to bind to `169.254.169.254`. Alternatively, perhaps the behavior on Windows will be different.

**Comment by osterman** [comment]
> Note that there's no .geodesic in my local /home/martaver. I thought originally it might be a permissions issue, but chmod 777 /home/martaver/.aws didn't make a difference, and then I noticed that .geodesic doesn't even exist in my local home dir.

I suspect that there's some other issue mounting since `.geodesic` folder is not getting created in  your home. I'll happily pair with you to get to the bottom of this issue. Ping me on [slack](https://slack.cloudposse.com) when you're online.

**Comment by osterman** [comment]
@Martaver I think your issues are all resolved now.
